### PR TITLE
Some refactoring in the julia code

### PR DESCRIPTION
**Pull request by giordano**
I'm taking this out of #2 because these changes are somewhat unrelated to (although propaedeutic for) the changes in that PR, and I'd like to get these in before continuing in #2.

### CODE REVIEW

**Review by pembacher — COMMENTED** [review]
In line 38 the version was parsed as a float before, now changed to int. Currently, indeed these are all ints, but I usually set floats for having the flexibility for sub-versions.

**Review by pembacher — COMMENTED** [review]
In the read-function, the version was parsed as a float before, now changed to int. In the LineageABCmodel-function, I sometimes have a check, if .==+Inf or isnan(.), which you made into isfinite(.). That's a different check, though - I'm fine with -Infs (e.g. line 1497, 1688, 1716).

**Review by pembacher — APPROVED** [review]

**Review by pembacher — APPROVED** [review]
Any reason (other than cleanliness), why whitespaces at the end would be removed? compiling-efficiency?

**Review by pembacher — COMMENTED** [review]
Any advantage to having vectors rather than Array{.,1}?

**Comment by giordano** [comment]
> In line 38 the version was parsed as a float before, now changed to int. Currently, indeed these are all ints, but I usually set floats for having the flexibility for sub-versions.

I don't think floating point numbers are a good abstraction for version numbers: besides the fact [floating point numbers are finicky](https://0.30000000000000004.com/), you won't be able to distinguish between version `3.1` and `3.10` and if you need to compare version numbers, the real number `5.2` is larger than `5.15` but if you interpret those as version numbers I guess you'd like `5.15` to come after `5.2`.  But perhaps you want to [`VersionNumber`](https://docs.julialang.org/en/v1/base/base/#Base.VersionNumber) instead?

```julia-repl
julia> v"5.15" > v"5.2"
true

julia> v"3.1" == v"3.10"
false

julia> parse(VersionNumber, "1.2")
v"1.2.0"

julia> parse(VersionNumber, "1.2.3")
v"1.2.3"
```

I can definitely change `Int` at https://github.com/Jamie-Dean-Lab/Lineage-analysis/blob/0539afe12a8e40509b608b3521a4189ec23febf2/readandanalysemultipleABCstatistics.jl#L38 to `VersionNumber` if you like this option.

> In the LineageABCmodel-function, I sometimes have a check, if .==+Inf or isnan(.), which you made into isfinite(.). That's a different check, though - I'm fine with -Infs (e.g. line 1497, 1688, 1716).

I'm assuming you're referring to https://github.com/Jamie-Dean-Lab/Lineage-analysis/blob/0539afe12a8e40509b608b3521a4189ec23febf2/LineageABCmodel.jl#L1465-L1467 https://github.com/Jamie-Dean-Lab/Lineage-analysis/blob/0539afe12a8e40509b608b3521a4189ec23febf2/LineageABCmodel.jl#L1497-L1499
https://github.com/Jamie-Dean-Lab/Lineage-analysis/blob/0539afe12a8e40509b608b3521a4189ec23febf2/LineageABCmodel.jl#L1688-L1690 https://github.com/Jamie-Dean-Lab/Lineage-analysis/blob/0539afe12a8e40509b608b3521a4189ec23febf2/LineageABCmodel.jl#L1716-L1718
but the check didn't change in practice: we first check if `probval_here` is `-Inf` and only if that's not true we enter the `elseif !isfinite(probval_here)` branch, so there's no way to enter this branch if `probval_here` is `-Inf`.  Or am I missing something else?

> Any reason (other than cleanliness), why whitespaces at the end would be removed? compiling-efficiency?

No, it's just my editor automatically removes extra whitespaces.

> Any advantage to having vectors rather than Array{.,1}?

No, `Vector{T}` is exactly an alias for `Array{T, 1}`, but it's shorter and doesn't have an extra parameter at the end.

**Comment by giordano** [comment]
@pembacher I think this is basically ready.  I dropped some minor non-functional unrelated changes and I introduced the other changes I told you today.  If you can push to `main` your local changes I can deal with the conflicts in this PR and then we should be good to go here.

**Review by pembacher — APPROVED** [review]

**Review by pembacher — APPROVED** [review]

**Review by pembacher — APPROVED** [review]

**Review by pembacher — APPROVED** [review]

**Pull request merged**
